(() => {
  "use strict";
  const KEY="su-loto-c2-contest-bets-v1",PRICE_KEY="su-loto-bet-price-v1",app=globalThis.SULotoApp;
  if(!app)return;
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return{}}},save=d=>localStorage.setItem(KEY,JSON.stringify(d));
  const fmt=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
  function inject(){const host=document.querySelector(".contest-tools-card .tool-stack")||document.getElementById("contests-view");if(!host||document.getElementById("su-loto-contest-bets"))return false;
    const box=document.createElement("section");box.id="su-loto-contest-bets";box.className="contest-bets-box";box.innerHTML=`<h3>Apostas por concurso</h3><p>Salve os jogos atualmente marcados como Apostado para um concurso específico.</p><label><span>Concurso</span><input id="su-loto-bet-contest" type="number" min="1" inputmode="numeric" placeholder="Ex.: 3750"></label><label><span>Valor por aposta</span><input id="su-loto-bet-price" type="number" min="0" step="0.01" value="${localStorage.getItem(PRICE_KEY)||"3.50"}"></label><div class="contest-bets-actions"><button id="su-loto-save-contest-bets" class="button primary" type="button">Registrar apostas atuais</button><button id="su-loto-delete-contest-bets" class="button danger" type="button">Excluir registro</button></div><div id="su-loto-bet-summary" class="contest-bets-summary">Nenhum concurso selecionado.</div>`;host.appendChild(box);
    const style=document.createElement("style");style.textContent=`.contest-bets-box{margin-top:14px;padding:16px;border:1px solid #eadff0;border-radius:16px;background:#fbf7fc}.contest-bets-box h3{margin:0 0 6px}.contest-bets-box p{margin:0 0 12px;color:#6b6470}.contest-bets-box label{display:grid;gap:6px;margin:10px 0;font-weight:800}.contest-bets-box input{font:inherit;padding:11px;border:1px solid #dfd2e5;border-radius:10px}.contest-bets-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.contest-bets-summary{margin-top:12px;padding:12px;border-radius:12px;background:#fff;border:1px solid #eadff0;line-height:1.5}@media(max-width:560px){.contest-bets-actions{grid-template-columns:1fr}}`;document.head.appendChild(style);
    const number=document.getElementById("su-loto-bet-contest"),price=document.getElementById("su-loto-bet-price"),summary=document.getElementById("su-loto-bet-summary");
    function render(){const n=String(number.value||"").trim(),row=load()[n];if(!n)return summary.textContent="Nenhum concurso selecionado.";if(!row)return summary.textContent=`Concurso ${n}: nenhuma aposta vinculada.`;summary.innerHTML=`<strong>Concurso ${n}</strong><br>${row.gameIds.length} jogos apostados • ${fmt(row.totalInvested)}<br><small>Registrado em ${new Date(row.savedAt).toLocaleString("pt-BR")}</small>`}
    number.addEventListener("input",render);price.addEventListener("change",()=>localStorage.setItem(PRICE_KEY,price.value));
    document.getElementById("su-loto-save-contest-bets").onclick=()=>{const n=Number(number.value),unit=Number(price.value);if(!Number.isInteger(n)||n<1)return alert("Informe um concurso válido.");if(!(unit>=0))return alert("Informe um valor válido.");const ids=app.games.filter(g=>app.states[g.id]==="apostado").map(g=>g.id);if(!ids.length&&!confirm("Nenhum jogo está marcado como Apostado. Salvar mesmo assim?"))return;const data=load();data[n]={contest:n,gameIds:ids,unitPrice:unit,totalInvested:ids.length*unit,savedAt:new Date().toISOString()};save(data);localStorage.setItem(PRICE_KEY,String(unit));render();app.toast?.("Apostas do concurso registradas");window.dispatchEvent(new CustomEvent("su:contest-bets-updated",{detail:data[n]}));};
    document.getElementById("su-loto-delete-contest-bets").onclick=()=>{const n=String(number.value||"").trim(),data=load();if(!n||!data[n])return;if(!confirm(`Excluir as apostas vinculadas ao concurso ${n}?`))return;delete data[n];save(data);render();app.toast?.("Registro de apostas excluído")};return true;}
  if(!inject()){const t=setInterval(()=>{if(inject())clearInterval(t)},300);setTimeout(()=>clearInterval(t),15000)}
  globalThis.SULotoContestBets={get:contest=>load()[String(contest)]||null,all:load};
})();