const CACHE="su-loto-c2-cloud-v11";
const ASSETS=["./","./index.html","./styles.css","./contests.css","./official-results.css","./data/games-1.js","./data/games-2.js","./data/games-3.js","./data/games-4.js","./data/games-5.js","./data/games-6.js","./data/ultimo-concurso.json","./data/concursos-oficiais.json","./contests.js","./official-results.js","./pwa-install-compat.js","./cloud-sync.js","./ecosystem-ui.js?v=5","./ecosystem-backup.js","./prize-analysis.js?v=2","./contest-bets.js?v=1","./ui-polish.js?v=1","./app.js","./manifest.json","./icon.svg"];
const LOADER="\n;/* SU_CLOUD_LOADER */import('./pwa-install-compat.js').then(()=>import('./cloud-sync.js')).then(()=>import('./ecosystem-ui.js?v=5')).then(()=>import('./ecosystem-backup.js')).then(()=>import('./prize-analysis.js?v=2')).then(()=>import('./contest-bets.js?v=1')).then(()=>import('./ui-polish.js?v=1')).catch(error=>console.error('SU Loto Cloud:',error));\n";
self.addEventListener("install",event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));self.skipWaiting()});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("su-loto-")&&key!==CACHE).map(key=>caches.delete(key)))));self.clients.claim()});
async function updateCache(request){try{const response=await fetch(request,{cache:"no-store"});if(response.ok){const cache=await caches.open(CACHE);await cache.put(request,response.clone())}return response}catch{return null}}
async function officialFast(request,event){const cache=await caches.open(CACHE);let response=await cache.match(request);if(response){event.waitUntil(updateCache(request));}else{response=await updateCache(request)}if(!response)return new Response(LOADER,{headers:{"Content-Type":"application/javascript; charset=utf-8"}});const source=await response.text();return new Response(source.includes("SU_CLOUD_LOADER")?source:source+LOADER,{status:200,headers:{"Content-Type":"application/javascript; charset=utf-8","Cache-Control":"no-store"}})}
async function navigationFast(request,event){const cache=await caches.open(CACHE);const cached=await cache.match("./index.html");const refresh=fetch(request,{cache:"no-store"}).then(response=>{if(response.ok)cache.put("./index.html",response.clone());return response}).catch(()=>null);if(cached){event.waitUntil(refresh);return cached}return(await refresh)||new Response("Aplicativo indisponível",{status:503})}
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetch(request,{cache:"no-store"});if(response.ok)await cache.put(request,response.clone());return response}catch{return(await cache.match(request))||new Response("Sem conexão",{status:503})}}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith("/official-results.js")){event.respondWith(officialFast(request,event));return}if(url.pathname.endsWith("/data/ultimo-concurso.json")||url.pathname.endsWith("/data/concursos-oficiais.json")){event.respondWith(networkFirst(request));return}if(request.mode==="navigate"){event.respondWith(navigationFast(request,event));return}event.respondWith(caches.match(request).then(cached=>{if(cached){event.waitUntil(updateCache(request));return cached}return updateCache(request).then(response=>response||new Response("Recurso indisponível",{status:503}))}))});